-- all icons i want to use in different parts of
-- my neovim config
local icons = {
  dashboard = {
    lazy = "󰒲 ",
    update = " ",
    sync = " ",
    mason = "  ",
    telescope = "  ",
    exit = " ",
    project = " ",
    mru = " ",
  },
  lualine = {
    left_bar = "▊ ",
    right_bar = " ▊",
    neovim_icon = " ",
    branch = "",
    add = " ",
    change = " ",
    delete = " ",
    lsp_icon = "lsp  ",
    error = " ",
    warn = " ",
    hint = " ",
    info = " ",
    select = " ",
    terminal = " ",
    replace = " ",
    copilot_enabled = " ",
    copilot_sleep = "󰒲 ",
    copilot_disabled = " ",
    copilot_warning = " ",
    copilot_unknown = " ",
    status_right_arch = "󰣇 ",
    status_right_pop = " ",
    status_right_mac = " ",
  },
  neotree = {
    default = " ",
    symlink = " ",
    bookmark = " ",
    folder = {
      arrow_closed = " ",
      arrow_open = " ",
      default = " ",
      open = " ",
      empty = " ",
      closed = " ",
      empty_open = " ",
      symlink = " ",
      symlink_open = " ",
      symlink_arrow = "  ",
    },
    file = {
      modified = "󱇨 ",
    },
    git = {
      unstaged = " ",
      staged = " ",
      unmerged = " ",
      renamed = " ",
      untracked = " ",
      deleted = " ",
      ignored = " ",
      conflict = "裂",
    },
  },
  mason = {
    installed = " ",
    pending = " ",
    uninstalled = " ",
  },
  gitblame = {
    author = " ",
    date = " ",
    summary = " ",
    uncomitted = "󱋽 ",
  },
}

return icons
