return {
  -- this is for DAPs, linters, and formatters
  -- LSP goes in the next section
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "ansible-lint",
        "astro-language-server",
        "bash-language-server",
        "beautysh",
        "black",
        "clangd",
        "cmake-language-server",
        "css-lsp",
        "curlylint",
        "debugpy",
        "deno denols",
        "docformatter",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "fixjson",
        "flake8",
        "gh",
        "gitlint",
        "gopls",
        "grammarly-languageserver",
        "helm-ls",
        "html-lsp",
        "jq",
        "json-lsp",
        "julia-lsp",
        "lemminx",
        "ltex-ls",
        "lua-language-server",
        "luacheck",
        "luaformatter",
        "marksman",
        "prettier",
        "ruff",
        "ruff-lsp",
        "rust-analyzer",
        "rustfmt",
        "rustywind",
        "shellcheck",
        "shfmt",
        "spectral-language-server",
        "sqlls",
        "stylua",
        "taplo",
        "terraform-ls",
        "typescript-language-server",
        "vim-language-server",
        "write-good",
        "xmlformatter",
        "yaml-language-server",
        "yamllint",
        "yq",
        "zls",
      },
    },
  },

  -- LSP goes here; DAP, linter, formatters go in mason
  {
    "neovim/nvim-lspconfig",
    opts = {
      ---@type lspconfig.options
      servers = {
        ansiblels = {},
        astro = {},
        bashls = {},
        clangd = {},
        cmake = {},
        cssls = {},
        denols = {},
        dockerls = {},
        gopls = {},
        grammarly = {},
        helm_ls = {},
        html = {},
        jsonls = {},
        julials = {},
        lemminx = {},
        ltex = {},
        lua_ls = {},
        marksman = {},
        ruff_lsp = {},
        rust_analyzer = {},
        sqlls = {},
        terraformls = {},
        tsserver = {},
        yamlls = {},
      },
      setup = {},
    },
  },

  -- lspsaga; not sure if i'll use it or not
  -- {
  --   "nvimdev/lspsaga.nvim",
  --   config = function()
  --     require("lspsaga").setup({
  --       -- add your config value here
  --     })
  --   end,
  -- },
}
