name: Lua Lint

on:
  pull_request:
    paths:
      - "**.lua"
  push:
    branches:
      - main
    paths:
      - "**.lua"

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # set up Lua (no cache params)
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: 5.1

      # cache luarocks dependencies
      - name: Cache Lua
        uses: actions/cache@v3
        with:
          path: ~/.lua
          key: ${{ runner.os }}-lua-${{ hashFiles('**/lua.lock') }}
          restore-keys: |
            ${{ runner.os }}-lua-

      # install luarocks and luacheck
      - name: Install luarocks
        run: sudo apt-get install luarocks

      - name: Install luacheck
        run: luarocks install luacheck

      # run luacheck
      - name: Run luacheck
        run: luacheck .
